### ISSUE TITLE
There is no GAN file in the models folder

### ISSUE THREAD

**Issue by fabacha** [illidanlab/FOSTER#1]
Hi.
I am trying to replicate your work and I realised that line 16 from the train file makes references to a GAN model that does not exist in your source code.

**from models.gan import Generator, Discriminator**

Can you please provide that to assist me in running the codes?
Thank you.

**Comment by Yu-shuyan** [comment]
Our main training file is not train.py in folder src, it is [foster.py](https://github.com/illidanlab/FOSTER/blob/main/foster.py). The running command can be seen in [README.md](https://github.com/illidanlab/FOSTER/blob/main/README.md). Sorry for the trouble that the file train.py has caused you, we have deleted it.

**Comment by fabacha** [comment]
Alright, thank you.
