### ISSUE TITLE
resnet_cifar10.pth is not available in the files

### ISSUE THREAD

**Issue by fabacha** [illidanlab/FOSTER#2]
Hi.
Can you please point me to where I can get the pretrained weights file:resnet_cifar10.pth.

Thank you!

**Comment by Yu-shuyan** [comment]
Do you mean you want the pre-trained model before testing? You can run the training command first, eg,
python foster.py --pd_nuser 50 --pu_nclass 3 --wk_iters 5 --model wrn --data stl --con_test_cls --no_track_stat --iter 300 --local_fc --use_external gen_inverse --method crossentropy --score OE --select_generator 1
to get the model, and then you can test the model.
