### ISSUE TITLE
OOD Data for Federated Learning.

### ISSUE THREAD

**Issue by fabacha** [illidanlab/FOSTER#3]
Hi!

Thank you for making your code open-source.

Please which variables represent the generated synthetic data for federated learning? I am having a difficult time figuring it out.

Thank you!

**Comment by Yu-shuyan** [comment]
oodz is the synthetic data produced by the generator as shown here https://github.com/illidanlab/FOSTER/blob/e828bdc7ddf0e3adc94474a27a181fb27a4ad900/VOS_virtual.py#L332C9-L332C13
ood_sample is the synthetic data after filtering as shown here
https://github.com/illidanlab/FOSTER/blob/e828bdc7ddf0e3adc94474a27a181fb27a4ad900/VOS_virtual.py#L377

**Comment by fabacha** [comment]
> oodz is the synthetic data produced by the generator as shown here https://github.com/illidanlab/FOSTER/blob/e828bdc7ddf0e3adc94474a27a181fb27a4ad900/VOS_virtual.py#L332C9-L332C13 ood_sample is the synthetic data after filtering as shown here
> 
> https://github.com/illidanlab/FOSTER/blob/e828bdc7ddf0e3adc94474a27a181fb27a4ad900/VOS_virtual.py#L377

Thank you very much for the response.
